version: '3.3'
services:
#  web:
#    image: nginx:1.17.0-alpine
#    restart: always
#    depends_on:
#      - php
#    volumes:
#      - .:/app
#      - ./.docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - php
#    ports:
#      - '85:80'

#  php:
#    build: ./.docker/php
#    restart: always
##    environment:
##      XDEBUG_CONFIG: remote_host=172.19.0.1
#    depends_on:
#      - db
##      - rabbit
#    volumes:
#      - ./.docker/config/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
#      - .:/app:delegated
#      - ./.docker/data/php-home:/home/www-data

  db:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: dockerdb
      MYSQL_ROOT_PASSWORD: dockerdb
    volumes:
#      - ./.docker/config/mysql.cnf:/etc/mysql/conf.d/local.cnf
#      - ./docker/config/my.cnf:/root/.my.cnf
      - ./.docker/data/db:/var/lib/mysql
    ports:
      - '3309:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    links:
      - db:db
